#!/bin/sh

PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
STAGED_FILES_CMD=`git diff --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`

# Determine if a file list is passed
if [ "$#" -eq 1 ]
then
	oIFS=$IFS
	IFS='
	'
	SFILES="$1"
	IFS=$oIFS
fi
SFILES=${SFILES:-$STAGED_FILES_CMD}

printf "Checking PHP Lint...\n"
for FILE in $SFILES
do
	php -l -d display_errors=0 $PROJECT/$FILE
	if [ $? != 0 ]
	then
		printf "Fix the error (php) before commit.\n"
		exit 1
	fi
	FILES="$FILES $PROJECT/$FILE"
done

if [ "$FILES" != "" ]
then
    if command -v phpcs > /dev/null 2>&1; then
        printf "Running Code Sniffer...\n"
        phpcs --encoding=utf-8 $FILES
        if [ $? != 0 ]
        then
            printf "Fix the error (phpcs) before commit.\n"
            exit 1
        fi
    else
        printf "Recommand installing phpcs.\n"
        exit 0
    fi
fi

exit $?
